Add Azure OpenAI bot and other finetune
yihong0618/xiaogpt pull request #222
Opened 2023-04-13 05:56 UTC by changeforan

- 添加了对Azure OpenAI的支持
- 去掉了唤醒词，默认所有问题都会query bot
- 优化了静音逻辑，更加快速的打断小爱同学自己的回答

2023-04-13 06:04 UTC, yihong0618 requested changes

2023-04-13 06:04 UTC, yihong0618 commented on xiaogpt/bot/azureopenai_bot.py
> +    system_msg= {"role": "system", "content": "你是一个语音助手，你的名字叫小爱同学，你的回答需要方便被朗读。"}
nice
can you make it to config?
你是一个语音助手，你的名字叫小爱同学，你的回答需要方便被朗读

2023-04-13 06:04 UTC, yihong0618 commented on xiaogpt/xiaogpt.py
> +            not query.startswith(WAKEUP_KEYWORD)
why this change?

2023-04-13 06:04 UTC, yihong0618 commented on xiaogpt/xiaogpt.py
> +                await asyncio.sleep(0.1)
0.1 有点短。。。我们是否可以让用户改这个？

2023-04-13 06:31 UTC, frostming commented
Azure Open AI已经在openai层面做了很好的兼容，我不明白为啥需要独立一个bot出来（大部分和chatgpt api是一样的）

2023-04-13 13:17 UTC, changeforan commented
> Azure Open AI已经在openai层面做了很好的兼容，我不明白为啥需要独立一个bot出来（大部分和chatgpt api是一样的）

你是指用gpt-3 bot兼容Azure OpenAI么，我感觉是不行的
请参考这篇：[Learn how to work with the ChatGPT and GPT-4 models](https://learn.microsoft.com/en-us/azure/cognitive-services/openai/how-to/chatgpt?pivots=programming-language-chat-completions)

其中提到：
>If you try to interact with the models the same way you did with the older model series, the models will often be verbose and provide less useful responses.

2023-04-13 14:03 UTC, yihong0618 commented on xiaogpt/xiaogpt.py
> +            not query.startswith(WAKEUP_KEYWORD)
@changeforan 但你这样就把小爱正常的功能屏蔽掉了，所以我们设计的用户可以自己改关键词，而我们需要有个关键词，这样没有更改能力的用户也可以有稍微完整的体验。

2023-04-14 00:49 UTC, frostming requested changes

2023-04-14 00:49 UTC, frostming commented on xiaogpt/bot/azureopenai_bot.py
> +            history_tokens = self.num_tokens_from_messages(self.history)
这个变量你只是计算了，并没有在任何地方**使用**它。为此引入一个**Rust build**的依赖。这不合适

2023-04-14 00:49 UTC, frostming commented on xiaogpt/bot/azureopenai_bot.py
> +            max_tokens=self.max_response_tokens,
self.max_response_tokens变量未定义

2023-04-14 00:51 UTC, frostming commented
建议这个PR只保留Azure OpenAI的部分，其他的改动需要另行讨论和PR。这样我们可以更快地merge

2023-04-14 00:53 UTC, frostming commented on xiaogpt/bot/azureopenai_bot.py
> +            max_tokens=self.max_response_tokens,
这里传参请参考ChatGPTBot，参数大部分不用写死

2023-04-14 16:41 UTC, changeforan commented
Update:
根据comment，去除了与Azure OpenAI无关的所有改动。删除了单独的Azure bot，仅在现有的`chatgptapi_bot`里兼容Azure OpenAI

2023-04-16 02:04 UTC, frostming commented on xiaogpt/bot/chatgptapi_bot.py
> +            kwargs["deployment_id"] = self.deployment_id
这个deployment_id和engine是一个意思吗，我在azure文档里只看到engine，没看到这个参数

2023-04-16 02:36 UTC, changeforan commented on xiaogpt/bot/chatgptapi_bot.py
> +            kwargs["deployment_id"] = self.deployment_id
嗯，是一个意思。[engine = params.pop("engine", deployment_id)](https://github.com/openai/openai-python/blob/e7ee4daaa5b2f4b90c519faee993377ab691559d/openai/api_resources/abstract/engine_api_resource.py#L74)
我觉得用deployment_id可以避免engine和model的误解。

2023-04-17 00:49 UTC, merged