add --config config.json support
yihong0618/xiaogpt pull request #40
Opened 2023-03-02 14:30 UTC by pjq

添加 config.txt

2023-03-02 14:46 UTC, yihong0618 commented on README.md
> +python3 xiaogpt.py
since its json why not config.json

2023-03-02 14:46 UTC, yihong0618 commented on xiaogpt.py
> +    # init the --config config.txt.example
ditto

2023-03-02 15:10 UTC, pjq commented on README.md
> +python3 xiaogpt.py
Good catchup

2023-03-02 15:13 UTC, pjq commented on README.md
> +python3 xiaogpt.py
updated

2023-03-02 15:13 UTC, pjq commented on xiaogpt.py
> +    # init the --config config.txt.example
updated

2023-03-03 06:59 UTC, yihong0618 requested changes

2023-03-03 06:59 UTC, yihong0618 commented on xiaogpt.py
> +    # update options with config
else raise

2023-03-03 06:59 UTC, yihong0618 commented on xiaogpt.py
> +
in the `if`

2023-03-03 11:26 UTC, CroMarmot commented
反正这段代码,我的理解是一旦传了`--config`,那么`config`中配置了的参数就会覆盖对应的命令行参数,也就是`config > cli > clidefault` ,  不只是 #48  

https://github.com/pjq/ChatGPT-MiSpeaker/blob/5983c5c6d1a1a38f421ed3ce257fcff2991de192/xiaogpt.py#L419-L429

2023-03-03 11:27 UTC, yihong0618 commented
> --con


> 反正这段代码,我的理解是一旦传了`--config`,那么`config`中配置了的参数就会覆盖对应的命令行参数,也就是`config > cli > clidefault` , 不只是 #48
> 
> https://github.com/pjq/ChatGPT-MiSpeaker/blob/5983c5c6d1a1a38f421ed3ce257fcff2991de192/xiaogpt.py#L419-L429

那不太好，--args > config > default 更合理些。

2023-03-03 12:52 UTC, pjq commented
@CroMarmot @yihong0618  你们的理解是对的，这个--config 确实会覆盖其它设置，我改了一下

2023-03-03 13:05 UTC, pjq commented
目前这个实现会是
- cli>default>config

2023-03-03 13:13 UTC, yihong0618 requested changes

2023-03-03 13:13 UTC, yihong0618 commented on README.md
> +如果想通过单一配置文件启动也是可以的, 可以通过--config参数指定配置文件, config文件必须是合法的JSON格式
我们可以把顺序加一下告诉用户

2023-03-03 13:13 UTC, yihong0618 commented on xiaogpt.py
> +        raise Exception(f"{options.config} doesn't exist")
这块逻辑好像不对，我的意思是
如果放了 options.config 但是出错了  raise
```python
if options.config:
   if os.path.exists(options.config):
    try:
        do_somthing
    except:
       raise
    else:
        raise Exception("something")
```

2023-03-03 13:22 UTC, pjq commented on xiaogpt.py
> +        raise Exception(f"{options.config} doesn't exist")
嗯，try: except, 这里可能不用加，默认会打印error stack?

2023-03-03 13:24 UTC, pjq commented on README.md
> +如果想通过单一配置文件启动也是可以的, 可以通过--config参数指定配置文件, config文件必须是合法的JSON格式
是的，支持多种类型参数配置，感觉容易不好控制

2023-03-03 15:02 UTC, CroMarmot commented
不一定有时间哈，我就不成为Collaborator了，declined了邀请。 大概看了一下，应该是对的，（我这边没有实际运行，都在静态看代码。）

就是这里从逻辑看，实际是在看argparse 的对应字段的`not`, 也就是如果有store_false应该就会有问题 虽然现在并没有, python3也不太熟，不知道有没有办法能 让argparse 在未传递的时候保持None或者直接没有对应字段了。不过目前的支持应该是没问题的。

2023-03-03 15:55 UTC, yihong0618 commented
> 就不成为Collaborator了，declined了邀请。 大概看了一下，应该是对的，（我这边没有实际运行，都在静态看代码。）

好的，没问题

2023-03-03 15:55 UTC, merged